@startuml
left to right direction
:Utilisateur:
:Visiteur:
:Administrateur:

Utilisateur --|> Visiteur
Administrateur --|> Utilisateur

rectangle {
(créer un compte)
(se connecter)
(consulter le leaderboard)
(consulter la liste des jeux)
(consulter la liste des challenges par jeu)
(récupérer son mot de passe)
(créer un challenge)
(modifier un challenge)
(supprimer son challenge)
(liker un jeu)
(liker un  challenge)
(se déconnecter)
(participe à un challenge)
(supprimer ou modifier un challenge)
(ajouter ou supprimer un jeu)
(supprimer un utilisateur)
}

Visiteur-->(créer un compte)
Visiteur-->(se connecter)
Visiteur-->(consulter le leaderboard)
Visiteur-->(consulter la liste des jeux)
Visiteur-->(consulter la liste des challenges par jeu)
Visiteur-->(récupérer son mot de passe)
Utilisateur-->(se déconnecter)
Utilisateur-->(créer un challenge)
Utilisateur-->(modifier un challenge)
Utilisateur-->(supprimer son challenge)
Utilisateur-->(liker un jeu)
Utilisateur-->(liker un  challenge)
Utilisateur-->(participe à un challenge)
Administrateur-->(supprimer ou modifier un challenge)
Administrateur-->(ajouter ou supprimer un jeu)
Administrateur-->(supprimer un utilisateur)


@enduml