###
# GET all games
GET http://localhost:3000/games
###
# GET one game
GET http://localhost:3000/games/13
###
# GET all challenges
GET http://localhost:3000/challenges
###
# GET one challenge
GET http://localhost:3000/challenges/2
###
# GET one user with challenges created
GET http://localhost:3000/users
###
# GET one user with challenges created
GET http://localhost:3000/users/1
###

###
### CREATE one challenge
POST http://localhost:3000/challenges
Content-Type: application/json

{
  "title": "test",
  "description": "Terminer"
 
}