###
# GET all games
GET http://localhost:3000/games
###
# GET one game
GET http://localhost:3000/games/13
###
# GET all challenges
GET http://localhost:3000/challenges
###
# GET one challenge
GET http://localhost:3000/challenges/2
###
# GET one user with challenges created
GET http://localhost:3000/users
###
# GET one user with challenges created
GET http://localhost:3000/users/1
###

###
### CREATE one challenge
POST http://localhost:3000/challenges
Content-Type: application/json

{
  "title": "test",
  "description": "Terminer"
 
}
### CREATE one user
POST http://localhost:3000/register
Content-Type: application/json

{
  
    "pseudo": "bibi_user",
    "lastname": "c",
    "firstname": "Jc",
    "email": "jc@example.com",
    "password": "password123",
    "birthdate": "1990-01-01T00:00:00.000Z",
    "role_id": 9
 
}