###
# GET all games
GET http://localhost:3000/games
###
# GET one game
GET http://localhost:3000/games/2
###
# GET all challenges
GET http://localhost:3000/challenges
###
# GET all challenges top-liked
GET http://localhost:3000/challenges/top-liked
###
# GET one challenge
GET http://localhost:3000/challenges/1
###
# GET one user with challenges created
GET http://localhost:3000/users

###
# GET one user with challenges created
GET http://localhost:3000/users/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Nywicm9sZSI6InVzZXIiLCJpYXQiOjE3NjE4MzA5MzQsImV4cCI6MTc2MTgzNDUzNH0.yLTMRm3peWiBg7e1mMRAaYiDNIjLI-FNBokVUPZgnys
###

###
### CREATE one challenge
POST http://localhost:3000/games/2/challenges
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Nywicm9sZSI6InVzZXIiLCJpYXQiOjE3NjE4MzQ3MjAsImV4cCI6MTc2MTgzODMyMH0.MyZvxtDjfMmEeQMkHvm6Uem2VdxHIr546yds1WRBiJU
Content-Type: application/json

{
  "title": "test perm 3",
  "description": "Terminer le jeu en difficile x"
 
}
### CREATE one user
POST http://localhost:3000/register
Content-Type: application/json

{
  
    "pseudo": "bibi",
    "lastname": "bibi",
    "firstname": "bibi",
    "email": "bibi@hotmail.com",
    "password": "azerty321",
    "birthdate": "1990-01-01T00:00:00.000Z",
    "role_id": 1
 
}

### CREATE userparticipation to one challenge
POST http://localhost:3000/challenges/22/participate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwicm9sZSI6InVzZXIiLCJpYXQiOjE3NjE4NDEyNjYsImV4cCI6MTc2MTg0NDg2Nn0.g0MKWsbC8lMky73FPreCV6gT1ar3xIjCo30-wHyjtiw
Content-Type: application/json

{  
    "proof": "https://e.xx/nts_win"
}

### CREATE Sign in for your account
POST http://localhost:3000/signin
Content-Type: application/json

{
  "email":"test@hotmail.com",
  "password":"azerty321"
}
### GET one user with challenges created
GET http://localhost:3000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYxNTczODAyLCJleHAiOjE3NjE1Nzc0MDJ9.OCX6g7mTfvJk-lN3brR33c7lMPucAgg69p2fQv4zlac
Content-Type: application/json



### UPDATE userparticipation to one challenge
PATCH http://localhost:3000/challenges/23/participate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Nywicm9sZSI6InVzZXIiLCJpYXQiOjE3NjE4NDA5NTYsImV4cCI6MTc2MTg0NDU1Nn0.hUwNMqPbBVMOhFne_YkqDXzWZKYnubanaDlcbjj3RRk
Content-Type: application/json

{  
    "proof": "https://xxxxx.com/proof/bibi_difficult.mp4" 
    
 
}
### DELETE userparticipation to one challenge
DELETE http://localhost:3000/challenges/22/participate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Nywicm9sZSI6InVzZXIiLCJpYXQiOjE3NjE4MzQ4ODIsImV4cCI6MTc2MTgzODQ4Mn0.BWhuBmw7_pkr928vH9E2Ff1qn12XUlIrfOKBl6yn8qc

### Update one challenge
PATCH http://localhost:3000/challenges/24
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Nywicm9sZSI6InVzZXIiLCJpYXQiOjE3NjE4MzQ4ODIsImV4cCI6MTc2MTgzODQ4Mn0.BWhuBmw7_pkr928vH9E2Ff1qn12XUlIrfOKBl6yn8qc
Content-Type: application/json

{
  "description": "rFinir le jeu"
}

###
# DELETE one challenge
DELETE  http://localhost:3000/challenges/24
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Nywicm9sZSI6InVzZXIiLCJpYXQiOjE3NjE4MzQ4ODIsImV4cCI6MTc2MTgzODQ4Mn0.BWhuBmw7_pkr928vH9E2Ff1qn12XUlIrfOKBl6yn8qc
